### ISSUE TITLE
add TriggerSender

### ISSUE THREAD

**Issue by steelec** [neuralabc/spft-java#5]
Create TriggerSender class in hardware and pull all the way through to the Trial level as per discussion w/ @theHilikus
skeleton outlined in  [df91dc31ad12553760eff484f6dfabb954cda9b9](https://github.com/neuralabc/spft-java/commit/df91dc31ad12553760eff484f6dfabb954cda9b9)

**Comment by steelec** [comment]
implemented in https://github.com/neuralabc/spft-java/tree/enh-trigger, awaiting final device testing for merge

**Comment by steelec** [comment]
@ajhelum to confirm:
- [x] inclusion of / enabling of trigger does not affect data recording
- [x] inclusion of / enabling of trigger does not affect temporal precision of program (including smoothness of display to monitor)
- [x] inclusion of / enabling of trigger does not affect CPU usage (which could result in any of the above)
- [x] arduino trigger device does not affect EMG
- [x] arduino trigger device does not affect EEG

**Comment by steelec** [comment]
> implemented in https://github.com/neuralabc/spft-java/tree/enh-trigger, awaiting final device testing for merge

note other changes in this branch will include altering the meaning of presentation frequency to refer to # milliseconds for displaying each element of a sequence (from Hz, which was less precise) and likely some intermediate implementation of dynamic time warping ( #6 )

**Comment by ajhelum** [comment]
Arduino trigger device is receiving trigger signals from SPFT for all testing files (yaml) smoothly, in one java session. (no need to open fresh session for running separate files)
Tested with 1.4 jar (recent as of May  03 2023).
No trigger delays observed.

**Comment by steelec** [comment]
thank you for the testing, I think this is ready for merge into main

**Comment by steelec** [comment]
included here: #8

**Comment by steelec** [comment]
now #8 merged into main
